nelmio_api_doc:
    documentation:
        info:
            title: swagger
            description: Swagger
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api # Accepts routes under /api except /api/doc
